### PR TITLE
Italian translation 

### PR DESCRIPTION
**Pull request by Matita008**

### CODE REVIEW

**Comment by BSp-2** [comment]
Hm you know, you should open pull request only after finishing the bundle

**Comment by Kev-Vily** [comment]
> Hm you know, you should open pull request only after finishing the bundle

ey, in my mindus indo community, we're quite open draft pr so we can edit it later, it's because people have different amounts of time to working. i think it is fine by me though. i dunno about catana opinion for this.

**Comment by BSp-2** [comment]
> > Hm you know, you should open pull request only after finishing the bundle
> 
> ey, in my mindus indo community, we're quite open draft pr so we can edit it later, it's because people have different amounts of time to working. i think it is fine by me though. i dunno about catana opinion for this.

I mean, you can always edit the fork without the request, and then just pull the finished thing, but everyone does that as they want so yeah... I translated everything into a txt file and then copypasted in 1 go 💀💀

**Comment by Catana791** [comment]
@Matita008 is this still being worked on?
If so, please send some updates here every now and then. 
Otherwise, automation will close this automatically after a while.

**Comment by Matita008** [comment]
> @Matita008 is this still being worked on?
> If so, please send some updates here every now and then. 
> Otherwise, automation will close this automatically after a while.

yup, but this week was a little busy with school, will add more next Saturday

**Pull request closed without merging**
